; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32@6.4.0
framework = arduino
monitor_speed = 115200
debug_build_flags = -Os
lib_deps = 
	https://github.com/suchmememanyskill/esp32-smartdisplay#9c1d737
	bblanchon/ArduinoJson@^7.0.0
	plageoj/UrlEncode@^1.0.1
	knolleary/PubSubClient@^2.8
	WiFiClientSecure
monitor_filters = esp32_exception_decoder
build_flags = 
	-DLV_CONF_PATH="../../../../src/conf/lv_conf.h"
extra_scripts = 
	pre:extract_commit.py

[env:native-sdl]
platform = native
framework =
lib_deps =
	https://github.com/suchmememanyskill/lvgl
	bblanchon/ArduinoJson@^7.0.0
	plageoj/UrlEncode@^1.0.1
	knolleary/PubSubClient@^2.8
build_flags = 
	-Wno-microsoft-include
	-DSCREEN_WIDTH=800
	-DSCREEN_HEIGHT=480
	-DNATIVE_SDL
	-lSDL2
	-DLV_CONF_PATH="../../../../src/conf/lv_conf.h"
	-D LV_LOG_PRINTF=1
	; Add recursive dirs for hal headers search
	!python -c "import os; print(' '.join(['-I {}'.format(i[0].replace('\x5C','/')) for i in os.walk('hal/sdl2')]))"

        -I support/
	-D ARDUINO_BOARD="\"native"\"
	; SDL drivers options
	-D LV_LVGL_H_INCLUDE_SIMPLE
	-D LV_DRV_NO_CONF
	-D LV_USE_SDL
	-D SDL_HOR_RES=480
	-D SDL_VER_RES=320  
	-D SDL_ZOOM=1
	-D LV_SDL_INCLUDE_PATH="\"SDL2/SDL.h\""

        -DCYD_SCREEN_HEIGHT_PX=240
        -DCYD_SCREEN_WIDTH_PX=320
        -DCYD_SCREEN_GAP_PX=8
        -DCYD_SCREEN_MIN_BUTTON_HEIGHT_PX=35
        -DCYD_SCREEN_MIN_BUTTON_WIDTH_PX=35
        -DCYD_SCREEN_FONT=lv_font_montserrat_14
        -DCYD_SCREEN_FONT_SMALL=lv_font_montserrat_10
        -DCYD_SCREEN_SIDEBAR_SIZE_PX=40
        -DCYD_SCREEN_DISABLE_TOUCH_CALIBRATION=1
        -DCYD_SCREEN_DISABLE_INVERT_COLORS=1
	-DCYD_SCREEN_DISABLE_TIMEOUT=1

	; LVGL memory options, setup for the demo to run properly
	;-D LV_MEM_CUSTOM=1
	;-D LV_MEM_SIZE="(128U * 1024U)"
		
extra_scripts = 
	pre:support/sdl2_paths.py ; Tries to find SDL2 include and lib paths on your system - specifically for MacOS w/ Homebrew
	post:support/sdl2_build_extra.py
# You can override SCREEN_WIDTH and SCREEN_HEIGHT at build time with:
#   pio run -e native-sdl --target clean -- -DSCREEN_WIDTH=1024 -DSCREEN_HEIGHT=600

[env:esp32-2432S028R]
board = esp32-2432S028R
lib_deps = 
	SPI
	https://github.com/suchmememanyskill/lvgl
	https://github.com/Bodmer/TFT_eSPI.git
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
	bblanchon/ArduinoJson@^7.0.0
	plageoj/UrlEncode@^1.0.1
	knolleary/PubSubClient@^2.8
	WiFiClientSecure

[env:esp32-3248S035C]
board = esp32-3248S035C
lib_deps = 
	SPI
	https://github.com/suchmememanyskill/lvgl
	https://github.com/Bodmer/TFT_eSPI.git
	https://github.com/OperatorB/gt911-arduino-fixed-reset.git
	bblanchon/ArduinoJson@^7.0.0
	plageoj/UrlEncode@^1.0.1
	knolleary/PubSubClient@^2.8
	WiFiClientSecure

[env:esp32-3248S035C-V]
board = esp32-3248S035C-vertical
lib_deps = 
	SPI
	https://github.com/suchmememanyskill/lvgl
	https://github.com/Bodmer/TFT_eSPI.git
	https://github.com/OperatorB/gt911-arduino-fixed-reset.git
	bblanchon/ArduinoJson@^7.0.0
	plageoj/UrlEncode@^1.0.1
	knolleary/PubSubClient@^2.8
	WiFiClientSecure

[env:esp32-2432S024C-SD]
board = esp32-2432S024C-smartdisplay

[env:esp32-2432S028Rv1-SD]
board = esp32-2432S028RV1-smartdisplay

[env:esp32-2432S028Rv2-SD]
board = esp32-2432S028RV2-smartdisplay

[env:esp32-2432S028Rv3-SD]
board = esp32-2432S028RV3-smartdisplay

[env:esp32-2432S032C-SD]
board = esp32-2432S032C-smartdisplay

[env:esp32-3248S035C-SD]
board = esp32-3248S035C-smartdisplay

[env:esp32-4827S043C-SD]
board = esp32-4827S043C-smartdisplay

[env:esp32-4827S043R-SD]
board = esp32-4827S043R-smartdisplay

[env:esp32-8048S043C-SD]
board = esp32-8048S043C-smartdisplay

[env:esp32-8048S043C-SD-alt]
board = esp32-8048S043C-smartdisplay-alt

[env:esp32-2432S022C-SD-V]
board = esp32-2432S022C-vertical

[env:esp32-CROWPANEL-28R]
board = esp32-CROWPANEL-28R
lib_deps = 
	SPI
	https://github.com/suchmememanyskill/lvgl
	https://github.com/Bodmer/TFT_eSPI.git
	bblanchon/ArduinoJson@^7.0.0
	plageoj/UrlEncode@^1.0.1
	knolleary/PubSubClient@^2.8
	WiFiClientSecure

[env:esp32-CROWPANEL-35C]
board = esp32-CROWPANEL-35C
lib_deps = 
	SPI
	https://github.com/suchmememanyskill/lvgl
	https://github.com/lovyan03/LovyanGFX@1.2.0
	bblanchon/ArduinoJson@^7.0.0
	plageoj/UrlEncode@^1.0.1
	knolleary/PubSubClient@^2.8
	WiFiClientSecure

[env:esp32-JC2432W3-28C]
board = esp32-JC2432W328C
lib_deps = 
	SPI
	https://github.com/suchmememanyskill/lvgl
	https://github.com/Bodmer/TFT_eSPI.git
	bblanchon/ArduinoJson@^7.0.0
	plageoj/UrlEncode@^1.0.1
	knolleary/PubSubClient@^2.8
	WiFiClientSecure


